# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: iouali <iouali@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/13 09:12:15 by gtoubol           #+#    #+#              #
#    Updated: 2023/01/23 20:56:34 by iouali           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Volumes
# ------------------------------------------------------------------------
volumes:
  frontend-node-modules:
    driver: local
  back_data:
    name: back_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${TR_BACK_SRCS}"
  db_data:
    driver: local

# Networks
# ------------------------------------------------------------------------
networks:
  backend-net:
    name: "backend-net"
    driver: "bridge"


# Servicies
# ------------------------------------------------------------------------
services:
  frontend:
    image: notrexp_frontend:dev-latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: bash -c "yarn serve"
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend
      - "frontend-node-modules:/frontend/node_modules"
    depends_on:
      -  database
    env_file:
      - .env

  # --------------------------
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - "back_data:/root/srcs"
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost:3000"]
    environment:
      - DOMAIN=${DOMAIN}
      - FRONT_DOMAIN=${FRONT_DOMAIN}
      - API_UID=${API_UID}
      - API_SECRET=${API_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRESIN=${JWT_EXPIRESIN}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_USER}

  # --------------------------
  database:
    container_name: "database"
    image: postgres:alpine
    restart: always
    networks:
      - backend-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - db_data:/var/lib/postgresql/data

  # --------------------------
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
    networks:
      - backend-net
